#image: "git-registry.service.t1-cloud.ru/cloud/registry-snapshot/portal/lab_tests:94d34a6e-25"
#image: "git-registry.service.t1-cloud.ru/cloud/registry-snapshot/portal/ubuntu_java_mvn_ssh:0b734ebe-1"
#image: "git-registry.service.t1-cloud.ru/cloud/registry-snapshot/portal/ubuntu-java-mvn-ssh:d39003fb-3" #checked for vulnrblts
image: "git-registry.service.t1-cloud.ru/cloud/registry-snapshot/portal/ubuntu-java-mvn-ssh-curl:367b4f21-8" #checked for vulnrblts

stages:
  - test

variables:
  ENV:
    value: ""
    description: "Выбрать стенд (t1ift)"
  TEST:
    value: ""
    description: "-Dtest= VirtualMachineTest#vmList"
  GROUPS:
    value: ""
    description: "-Dgroups="
  THREAD_COUNT:
    value: "4"
    description: "-Djunit.jupiter.execution.parallel.config.fixed.parallelism=$THREAD_COUNT"
  MAVEN_OPTS_1:
    value: ""
    description: "if you need to bring new libs off the web fill in ALL OF THIS -Drepository=https://repo1.maven.org/maven2/"
  MAVEN_OPTS_2: "-Dtest=$TEST -Denv=$ENV $JAVA_PASS_TESTS -Dgroups=$GROUPS -Djunit.jupiter.execution.parallel.config.fixed.parallelism=$THREAD_COUNT"
  MAVEN_OPTS_3: "-Dmaven.repo.local=.m2/repository"
  SSH_OPT: StrictHostKeyChecking=no

test:
  stage: test
  before_script:
    - export LANG=C.utf8
    - export SSHPASS="$SSH_PASS"
  # - apt-get update && apt-get install curl -y
  allow_failure: true
  #exit_codes: 0
  script:
    - mkdir -p .m2/repository/cassandra/jdbc-driver/1.4/
    - sshpass -e scp -r -o $SSH_OPT qa-admin@10.13.20.10:/home/qa-admin/.m2/* .m2
    #- ls -la .m2/repository/ > m2_after_first_scp_from_nginx
    - mvn compile $MAVEN_OPTS_1 $MAVEN_OPTS_3
    - cp src/main/resources/lib/cassandra-jdbc-driver-1.4.jar .m2/repository/cassandra/jdbc-driver/1.4/
    - mvn $MAVEN_OPTS_1 $MAVEN_OPTS_3 -X install:install-file -Dfile=.m2/repository/cassandra/jdbc-driver/1.4/cassandra-jdbc-driver-1.4.jar -DgroupId=cassandra -DartifactId=jdbc-driver -Dversion=1.4 -Dpackaging=jar || exit 0 #|| EXIT_CODE=$?
    #- export EXIT_CODE=0
    - echo -n "test $MAVEN_OPTS_1 $MAVEN_OPTS_2 $MAVEN_OPTS_3"
#    - timeout 180m mvn clean test $MAVEN_OPTS_1 $MAVEN_OPTS_2 $MAVEN_OPTS_3 3>&1 1>&2 2>&3 1>>$CI_PROJECT_DIR/clean_test_log | tee -a $CI_PROJECT_DIR/clean_test_log || exit 0 # || EXIT_CODE=$?
    #- export EXIT_CODE=0
  after_script:
    - export SSHPASS=$SSH_PASS
    - gzip $CI_PROJECT_DIR/clean_test_log
    - mkdir -p target/site/allure-maven-plugin/history
    - sshpass -e scp -r -o $SSH_OPT qa-admin@10.13.20.10:~/reports/allure-maven-plugin/history target/allure-results
    - mvn $MAVEN_OPTS_1 $MAVEN_OPTS_3 allure:report
    #- ls -la .m2/repository/ > m2_sent_to_nginx_after_allure_report
    - sshpass -e scp -r -o $SSH_OPT .m2/* qa-admin@10.13.20.10:~/.m2/
    - sshpass -e scp -r -o $SSH_OPT target/site/allure-maven-plugin qa-admin@10.13.20.10:~/reports
    - tar zcfv logs.tgz $CI_PROJECT_DIR/logs/
    - export CURR_DATE=`date +"%Y-%m-%d_%T" | sed -r 's/:/_/g'`
    - sshpass -e ssh -o $SSH_OPT qa-admin@10.13.20.10 "mkdir -p ~/reports/logs/$CURR_DATE/"
    - sshpass -e scp -o $SSH_OPT $CI_PROJECT_DIR/clean_test_log.gz qa-admin@10.13.20.10:~/reports/logs/$CURR_DATE/
    - sshpass -e scp -o $SSH_OPT $CI_PROJECT_DIR/logs.tgz qa-admin@10.13.20.10:~/reports/logs/$CURR_DATE/
    - sshpass -e scp -r -o $SSH_OPT target/site/allure-maven-plugin/ qa-admin@10.13.20.10:~/reports/logs/$CURR_DATE
    - sshpass -e ssh -o $SSH_OPT qa-admin@10.13.20.10 "/home/qa-admin/json_parser.py reports/allure-maven-plugin/data/suites.json > ~/output.txt"
    - sshpass -e scp -o $SSH_OPT qa-admin@10.13.20.10:~/output.txt output.txt
    - echo -n "http://10.13.20.10/~qa-admin/logs/"
    - echo -n $CURR_DATE
    - echo "/allure-maven-plugin/"
    - curl -X POST -H 'Content-Type:application/json' -d @output.txt https://api.telegram.org/bot$TELE_TOKEN/sendMessage || exit 0 # || EXIT_CODE=$?
    #- export EXIT_CODE=0
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      when: never
    - when: on_success
#  artifacts:
#    when: always
#    paths:
#    - m2_after_first_scp_from_nginx
#    - m2_sent_to_nginx_after_allure_report
#    expire_in: 1 h

