stages:
  - run tests

pages:
  stage: "run tests"
  tags:
    - deb
    - rhel
  script:
    - /opt/apache-maven-3.6.0/bin/mvn test -Dcucumber.options="--tags @Smoke" -s src/settings/settings.xml -P Nexus -Denv=TEST
    paths:
      - public
  after_script:
    - /opt/apache-maven-3.6.0/bin/mvn allure:report -s src/settings/settings.xml -P Nexus -q
