### GRAPHS
GET http://d4-product-catalog.apps.d0-oscp.corp.dev.vtb/graphs/?per_page=1&page=1
Accept: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###
POST http://d4-product-catalog.apps.d0-oscp.corp.dev.vtb/graphs/
Content-Type: application/json
Accept: application/json

{
  "name": "eva",
  "title": "eva",
  "author": "eva",
  "description": "eva",
  "type": "creating",
  "graph": [],
  "version": "1.0.0"
}

> {%
    client.test("Request executed successfully", function() {
    client.assert(response.status === 201, "Response status is not 201");
    });
    client.global.set("graph_id", response.body.id);
%}

<> 2021-11-15T142023.201.json
<> 2021-11-15T141310.201.json
<> 2021-11-15T141043.201.json

###
GET http://d4-product-catalog.apps.d0-oscp.corp.dev.vtb/graphs/{{graph_id}}/
Accept: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###
PATCH http://d4-product-catalog.apps.d0-oscp.corp.dev.vtb/graphs/{{graph_id}}/
Content-Type: application/json
Accept: application/json

{
  "version": "1.0.5",
  "static_data": {
    "test": "test"
  },
  "damage_order_on_error": true
}

> {%
    client.test("Request executed successfully", function() {
    client.assert(response.status === 200, "Response status is not 200");
    })
%}

###
DELETE http://d4-product-catalog.apps.d0-oscp.corp.dev.vtb/graphs/{{graph_id}}/
Content-Type: application/json
Accept: application/json

> {%
    client.test("Request executed successfully", function() {
    client.assert(response.status === 204, "Response status is not 204");
    })
%}

